# Generated by Django 5.0.1 on 2025-02-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_botuser_first_name_botuserchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuserchannel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
