# Generated by Django 5.0.1 on 2025-02-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_botuserchannel_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteOptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='botapp.voteoptionitem')),
            ],
        ),
        migrations.CreateModel(
            name='VotePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='none', max_length=10)),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.voteoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.botuser')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.voteoptionitem')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.votepost')),
            ],
        ),
    ]
