# Generated by Django 5.0.1 on 2025-02-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_votepost_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteoptionitem',
            options={'ordering': ['created_at']},
        ),
    ]
